### ISSUE TITLE
missing `utils.py`  （找不到 utils.py模块）

### ISSUE THREAD

**Issue by VentusAislant** [SupritYoung/Zhongjing#18]
在 `train_rm.py` 中 有如下代码：from utils import (
    PairwiseDataCollatorWithPadding,
    PairwisePeftTrainer,
    LogCallback,
    load_pretrained,
    prepare_args,
    prepare_data,
    preprocess_data,
    compute_accuracy,
    plot_loss
)
这里的 `utils` 模块的代码是否缺失了呢，该如何微调呢，请作者指导，麻烦您了

**Comment by TianhaoCPU** [comment]
作者你好，我也遇到了相同的问题，请指导，麻烦您啦

**Comment by pipilia** [comment]
我也遇到了相同的问题
