### ISSUE TITLE
Source of pre-training data

### ISSUE THREAD

**Issue by bbsngg** [SupritYoung/Zhongjing#4]
Thanks for your work. I would like to know the source of KG, record and report data in the pre-training data. Can you provide it, please?

**Comment by SupritYoung** [comment]
We use the CMeKG Chinese medical knowledge graph, you can contact the author of the original paper to request . The medical record and report data can't share becuase of the Hospital Privacy Policy. But if you are interested in conducting academic research, we can discuss the details of collaboration. Email: suprit@foxmail.com.

**Comment by bbsngg** [comment]
Thanks for sharing!
